version: "3.7"

services:
    server:
      init: true
      container_name: pia-qbittorrent
      restart: unless-stopped
      cap_add:
          - NET_ADMIN
      volumes:
          - /mnt/500gb/DL/:/downloads
          - /mnt/500gb/qBitConf/:/config
          - /mnt/4tb/:/4tb
      ports:
          - 8199:8888
      environment:
          - REGION=south_africa
          - USER=USER
          - PASSWORD=PASSWORD
          - UID=3
          - GID=3
          - TZ=Africa/Johannesburg
      image: j4ym0/pia-qbittorrent
